print("hello world!")
print("umasaraswathi")
name = input ()
age = input()
print("My name is :",name)
print("My age is :",age)
#get input for variable name age and address
name = input ("enter name")
age = int(input("enter age"))
print("My name is :",name)
print("My age is :",age)
